version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

# sudo service redis-server stop // to stop redis case port already in use