version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
